apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxdeploy
  labels:
    environment: test
spec:
  replicas: 3
  selector:
    matchlabels:
      environment: test
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        environment: test
    spec:
      containers:
      - image: nginx:1.18
        name : nginx